### ISSUE TITLE
Abstract reader assumes single quantity/array for "times" and "length" results

### ISSUE THREAD

**Issue by pixelifytica** [indica-mcf/Indica#313]
Spotted a regression in `AbstractReader` whilst updating the `PPFReader` methods; it originally accepted different "times" and "length" results per quantity from the specific reader implementation, now has changed to a single result per instrument. This breaks anything with multiple sets of lines of sight in very different coordinates (e.g. JET bolometry and SXR with both vertical and horizontal arrays) where it doesn't make sense to use a single transform for the entire instrument.

The original implementation of `{q}_times` for time results but `length = {q: [...]}` for lengths didn't make sense to be different either, so we would need to standardise on something (in which case I'd lean towards the latter version).

This ties in to wanting to clarify the database results anyways, so @hakosaj and @marcosertoli what are your opinions on this? As part of #309 I'll "fix" `AbstractReader` to accept times and length as dictionaries, but lets discuss more to agree what to settle on properly!

**Comment by pixelifytica** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clarify database_results dictionary expectation in abstract_reader and simplify reading implementation specific reader (e.g. st40reader, ppfreader)](https://trello.com/c/IYDYrFtQ/48-clarify-databaseresults-dictionary-expectation-in-abstractreader-and-simplify-reading-implementation-specific-reader-eg-st40read)

**Comment by marcosertoli** [comment]
Hi Evie, no I would not do that change.

I've made it that way because each system **must** be treated separately. SXR H and V cameras are two different systems, so will have to be read separately.

**Comment by pixelifytica** [comment]
Ah I see the philosophy, and yep I can see how that simplifies things from the POV of the results dictionary. Ok I'll need to review which JET instruments have multiple systems gathered in that way (Bolometry, SXR and CXRS immediately come to mind, I don't think there are others) and roll that in with the general PPF updates in #309 .

**Comment by marcosertoli** [comment]
Great! You can check ST40 reader and look e.g. for the instruments SXRC_XY of which there are 2.

I see the reader method as being the method that will be used to read a specified system TYPE e.g. SXR camera, or TS or similar.

JET is a bit difficult because each system has strange, different database entries. But if you think of IMAS, identical system TYPES will have the same structure. We've done something similar, so all SXR systems have an identical structure, as do all BOLOMETERS or all LANGMUIR PROBES, etc.

But you have the IMPLEMENTATION QUANTITIES to fix that where needed.

Marco


________________________________
